### ISSUE TITLE
登壇会場の参加者表示の変更

### ISSUE THREAD

**Issue by santooooooo** [cloto-jp/cloto#82]
登壇会場の参加者表示を以下のように変更する。

- [x] 参加者の表示部分を画面の左上部側に配置する。
- [x] デフォルト時の表示部分は参加者全てののアイコン表示から参加人数にする。
- [x] 参加人数部分をクリックすることで参加人数の下部に参加者全員のアイコンが表示されるようにする。
- [x] 参加者のアイコンが登壇者の映像部分と重なり見えなくなっているので、アイコンが登壇者の映像部分の上にくるようにする

**Comment by a2h1r0** [comment]
developにmarge済み．
